services:
  - type: web
    name: upstox-streamlit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. marketdatafeedv3.proto
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    plan: free
