services:
  - type: web
    name: upstox-streamlit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m grpc_tools.protoc \
        -I./feeds_proto \
        --python_out=./feeds_proto \
        --grpc_python_out=./feeds_proto \
        ./feeds_proto/MarketDataFeedV3.proto
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    plan: free
