name: Build and Bundle React Frontend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Make build script executable and run it
        run: |
          chmod +x build_and_bundle.sh
          ./build_and_bundle.sh

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # You can add deploy steps after this if desired
