name: Keep Render Alive

on:
  schedule:
    # Every 15 minutes UTC from 4:30 AM to 10 AM UTC (9 AM to 3:30 PM IST)
    - cron: '*/3 3-10 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run keep-alive ping
        env:
          SERVICE_URL: ${{ secrets.SERVICE_URL }}
        run: python ping_service.py
